## Import Library

In [24]:
import tensorflow as tf

## Membuat Tensor dengan shape(5,5)

In [25]:
random_tensor = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97],shape=[5,5], dtype=tf.float32)

Tensor dengan nilai random

In [26]:
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)>

Tensor dengan nilai bilangan prima

In [27]:
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

## Menampilkan dimensi

Dimensi variabel "random_tensor" \
Dimensi variabel "prime_tensor"

In [28]:
print("Dimensi random_tensor :",random_tensor.shape)
print("Dimensi prime_tensor  :",prime_tensor.shape)

Dimensi random_tensor : (5, 5)
Dimensi prime_tensor  : (5, 5)


## Operasi Aritmetika

Menampilkan hasil perhitungan random_tensor dan prime_tensor

Penambahan

In [29]:
tf.add(random_tensor,prime_tensor).numpy()

array([[ 1.6761351,  3.9913368,  5.1402426,  8.257397 , 11.099923 ],
       [13.189833 , 16.712889 , 17.25864  , 24.871876 , 26.98955  ],
       [29.532698 , 35.727802 , 40.219627 , 43.94073  , 46.93835  ],
       [50.91575  , 59.61423  , 59.54891  , 66.11307  , 70.03259  ],
       [73.94832  , 78.30255  , 83.53915  , 88.4703   , 94.98946  ]],
      dtype=float32)

Pengurangan

In [30]:
tf.subtract(random_tensor,prime_tensor).numpy()

array([[ -2.323865 ,  -2.0086632,  -4.8597574,  -5.742603 , -10.900077 ],
       [-12.810167 , -17.287111 , -20.74136  , -21.128124 , -31.01045  ],
       [-32.467304 , -38.272198 , -41.780373 , -42.05927  , -47.06165  ],
       [-55.08425  , -58.38577  , -62.45109  , -67.88693  , -71.96741  ],
       [-72.05168  , -79.69745  , -82.46085  , -89.5297   , -99.01054  ]],
      dtype=float32)

Perkalian

In [31]:
tf.multiply(random_tensor,prime_tensor).numpy()

array([[  -0.64772975,    2.974011  ,    0.70121336,    8.801781  ,
           1.0991569 ],
       [   2.4678192 ,   -4.880903  ,  -33.08583   ,   43.053135  ,
         -58.303062  ],
       [ -45.48639   ,  -47.07136   ,  -31.995327  ,   40.451405  ,
          -2.8974664 ],
       [-110.465385  ,   36.23965   ,  -88.51661   ,  -59.42466   ,
         -68.68601   ],
       [  69.22724   ,  -55.098545  ,   44.748924  ,  -47.143356  ,
        -195.02203   ]], dtype=float32)

Pembagian

In [32]:
tf.divide(random_tensor,prime_tensor).numpy()

array([[-0.16193244,  0.33044565,  0.02804853,  0.17962816,  0.00908394],
       [ 0.01460248, -0.01688894, -0.0916505 ,  0.08138589, -0.06932587],
       [-0.04733235, -0.03438376, -0.01903351,  0.02187745, -0.00131166],
       [-0.03932552,  0.0104107 , -0.02378839, -0.01323784, -0.01362547],
       [ 0.01299066, -0.00882848,  0.00649571, -0.00595169, -0.02072718]],
      dtype=float32)

Pangkat

In [33]:
tf.pow(random_tensor,prime_tensor).numpy()

array([[ 1.0488846e-01,  9.7423530e-01,  5.4250133e-05,  4.9694390e+00,
         9.9160073e-12],
       [ 4.1572837e-10, -6.1216887e-10, -3.7746809e+04,  1.8296565e+06,
        -6.2446387e+08],
       [-1.4524903e+05, -7.3881514e+03, -3.8406979e-05,  7.2277203e-02,
        -0.0000000e+00],
       [-8.0235882e+16,  3.2477805e-13, -7.3011604e+09, -3.2266942e-04,
        -9.5127881e-02],
       [ 2.0780388e-02, -4.3403966e-13,  5.3885902e-23, -2.7460855e-25,
        -2.6379033e+29]], dtype=float32)

Logaritma

In [34]:
tf.math.log(random_tensor,prime_tensor).numpy()

array([[        nan, -0.0087008 , -1.964381  ,  0.22904386, -2.3033519 ],
       [-1.6616145 ,         nan,         nan,  0.62694085,         nan],
       [        nan,         nan,         nan, -0.06109876,         nan],
       [        nan, -0.48738366,         nan,         nan,         nan],
       [-0.05306501,         nan, -0.6177732 ,         nan,         nan]],
      dtype=float32)

## Nilai Maksimum dan Minimal Variabel random_tensor

Nilai Maksimum

In [35]:
print("Nilai Maksimum Kolom :",tf.argmax(random_tensor, axis=0).numpy())
print("Nilai Maksimum Baris :",tf.argmax(random_tensor, axis=1).numpy())

Nilai Maksimum Kolom : [4 0 4 1 0]
Nilai Maksimum Baris : [3 3 3 1 0]


Nilai Minimal

In [36]:
print("Nilai Minimal Kolom :",tf.argmin(random_tensor, axis=0).numpy())
print("Nilai Minimal Baris :",tf.argmin(random_tensor, axis=1).numpy())

Nilai Minimal Kolom : [3 2 1 3 4]
Nilai Minimal Baris : [0 4 0 0 4]


## Penggabungan Variable random_tensor dengan prime_tensor

Penggabungan Kolom

In [37]:
concat_kolom = tf.concat([random_tensor, prime_tensor], axis=0)

print(concat_kolom.numpy())


[[-3.2386488e-01  9.9133694e-01  1.4024267e-01  1.2573972e+00
   9.9923350e-02]
 [ 1.8983224e-01 -2.8711194e-01 -1.7413595e+00  1.8718754e+00
  -2.0104504e+00]
 [-1.4673029e+00 -1.2721989e+00 -7.8037381e-01  9.4073033e-01
  -6.1648224e-02]
 [-2.0842526e+00  6.1423135e-01 -1.4510920e+00 -8.8693523e-01
  -9.6740866e-01]
 [ 9.4831836e-01 -6.9744992e-01  5.3914368e-01 -5.2970064e-01
  -2.0105364e+00]
 [ 2.0000000e+00  3.0000000e+00  5.0000000e+00  7.0000000e+00
   1.1000000e+01]
 [ 1.3000000e+01  1.7000000e+01  1.9000000e+01  2.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  4.3000000e+01
   4.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  6.1000000e+01  6.7000000e+01
   7.1000000e+01]
 [ 7.3000000e+01  7.9000000e+01  8.3000000e+01  8.9000000e+01
   9.7000000e+01]]


Penggabungan Baris

In [38]:
concat_baris = tf.concat([random_tensor, prime_tensor], axis=1)

print(concat_baris.numpy())

[[-3.2386488e-01  9.9133694e-01  1.4024267e-01  1.2573972e+00
   9.9923350e-02  2.0000000e+00  3.0000000e+00  5.0000000e+00
   7.0000000e+00  1.1000000e+01]
 [ 1.8983224e-01 -2.8711194e-01 -1.7413595e+00  1.8718754e+00
  -2.0104504e+00  1.3000000e+01  1.7000000e+01  1.9000000e+01
   2.3000000e+01  2.9000000e+01]
 [-1.4673029e+00 -1.2721989e+00 -7.8037381e-01  9.4073033e-01
  -6.1648224e-02  3.1000000e+01  3.7000000e+01  4.1000000e+01
   4.3000000e+01  4.7000000e+01]
 [-2.0842526e+00  6.1423135e-01 -1.4510920e+00 -8.8693523e-01
  -9.6740866e-01  5.3000000e+01  5.9000000e+01  6.1000000e+01
   6.7000000e+01  7.1000000e+01]
 [ 9.4831836e-01 -6.9744992e-01  5.3914368e-01 -5.2970064e-01
  -2.0105364e+00  7.3000000e+01  7.9000000e+01  8.3000000e+01
   8.9000000e+01  9.7000000e+01]]


## Sorting secara DESCENDING

Variabel random_tensor

In [39]:
sort_random = tf.sort(random_tensor, direction="DESCENDING")

sort_random.numpy()


array([[ 1.2573972 ,  0.99133694,  0.14024267,  0.09992335, -0.32386488],
       [ 1.8718754 ,  0.18983224, -0.28711194, -1.7413595 , -2.0104504 ],
       [ 0.94073033, -0.06164822, -0.7803738 , -1.2721989 , -1.4673029 ],
       [ 0.61423135, -0.88693523, -0.96740866, -1.451092  , -2.0842526 ],
       [ 0.94831836,  0.5391437 , -0.52970064, -0.6974499 , -2.0105364 ]],
      dtype=float32)

Variabel prime_tensor

In [40]:
sort_prime = tf.sort(prime_tensor, direction="DESCENDING")

sort_prime.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)